// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CampoDATEenActa_Examen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoDATEenActa_Examen));
        
        string IMigrationMetadata.Id
        {
            get { return "201410082218433_Campo DATE en Acta_Examen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
