// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AgregaBarrioymodificaPersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregaBarrioymodificaPersona));
        
        string IMigrationMetadata.Id
        {
            get { return "201409230311056_Agrega Barrio y modifica Persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
