// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CamposbooleanosaNULLenPersonas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposbooleanosaNULLenPersonas));
        
        string IMigrationMetadata.Id
        {
            get { return "201409222349118_Campos booleanos a NULL en Personas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
