// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AgregaHorariosaCursos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregaHorariosaCursos));
        
        string IMigrationMetadata.Id
        {
            get { return "201504082249527_Agrega Horarios a Cursos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
