// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IdentificadordeInscripciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentificadordeInscripciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011309267_Identificador de Inscripciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
