// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PresentoDocumentacionparaInscripcion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PresentoDocumentacionparaInscripcion));
        
        string IMigrationMetadata.Id
        {
            get { return "201512142140461_Presento Documentacion para Inscripcion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
