// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EstadoenlibroenParciales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstadoenlibroenParciales));
        
        string IMigrationMetadata.Id
        {
            get { return "201510070004594_Estado en libro en Parciales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
