// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fechadepresentaciondedocumentacionparainscripcion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fechadepresentaciondedocumentacionparainscripcion));
        
        string IMigrationMetadata.Id
        {
            get { return "201512162334158_Fecha de presentacion de documentacion para inscripcion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
