// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AgregaEstadoDefinitivoaMateria_X_Curso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregaEstadoDefinitivoaMateria_X_Curso));
        
        string IMigrationMetadata.Id
        {
            get { return "201505300032537_Agrega Estado Definitivo a Materia_X_Curso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
