// <auto-generated />
namespace ColegioTerciario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Equivalencia_DetalleCambiaDetalle_Tipoainteger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Equivalencia_DetalleCambiaDetalle_Tipoainteger));
        
        string IMigrationMetadata.Id
        {
            get { return "201509220001405_Equivalencia_Detalle -- Cambia Detalle_Tipo a integer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
